_target_: vid2skill.common.drake_envs.franka_allegro_env.FrankaAllegroDrakeSystem

configs:
  _target_: vid2skill.common.config_classes.env_configs.FrankaAllegroDrakeSystemConfigs
  state_size: 59
  action_size: 23
  frame_skip: 20
  sim_dt: 0.001
  show_collision_geometries: false
  package_map:
    trifinger: "lcs_rl/drake_envs/trifinger_with_cube"

  urdfs:
    - "vid2skill/models/franka_allegro/franka_allegro.urdf"
    - "vid2skill/models/ycb/006_mustard_bottle.sdf"

  welded_links:
    - body_of_child_link: "franka_allegro"
      child_link: "panda_link0"
      body_of_parent_link: "WorldModelInstance"
      parent_link: "world"

  additional_joints: []

  contact_geoms:
    - model_1: "franka_allegro"
      body_1: "allegro_palm_link"
      collision_1: "allegro_palm_link_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_0"
      collision_1: "allegro_link_0_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_1"
      collision_1: "allegro_link_1_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_2"
      collision_1: "allegro_link_2_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_3"
      collision_1: "allegro_link_3_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_3_tip"
      collision_1: "allegro_link_3_tip_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_4"
      collision_1: "allegro_link_4_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_5"
      collision_1: "allegro_link_5_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_6"
      collision_1: "allegro_link_6_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_7"
      collision_1: "allegro_link_7_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_7_tip"
      collision_1: "allegro_link_7_tip_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_8"
      collision_1: "allegro_link_8_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_9"
      collision_1: "allegro_link_9_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_10"
      collision_1: "allegro_link_10_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_11"
      collision_1: "allegro_link_11_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_11_tip"
      collision_1: "allegro_link_11_tip_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_12"
      collision_1: "allegro_link_12_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_13"
      collision_1: "allegro_link_13_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_14"
      collision_1: "allegro_link_14_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_15"
      collision_1: "allegro_link_15_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "franka_allegro"
      body_1: "allegro_link_15_tip"
      collision_1: "allegro_link_15_tip_collision"
      model_2: "006_mustard_bottle"
      body_2: "base_link_mustard"
      collision_2: "box_collision"
    - model_1: "006_mustard_bottle"
      body_1: "base_link_mustard"
      collision_1: "point_collision1"
      model_2: "WorldModelInstance"
      body_2: "world"
      collision_2: "world_ground_plane"
    - model_1: "006_mustard_bottle"
      body_1: "base_link_mustard"
      collision_1: "point_collision3"
      model_2: "WorldModelInstance"
      body_2: "world"
      collision_2: "world_ground_plane"
    - model_1: "006_mustard_bottle"
      body_1: "base_link_mustard"
      collision_1: "point_collision5"
      model_2: "WorldModelInstance"
      body_2: "world"
      collision_2: "world_ground_plane"
    - model_1: "006_mustard_bottle"
      body_1: "base_link_mustard"
      collision_1: "point_collision7"
      model_2: "WorldModelInstance"
      body_2: "world"
      collision_2: "world_ground_plane"

  # task related config parameters
  target_pos_obj: [0.0, 0.0, 0.0325]
  target_axisangle_obj: [0.0, 0.0, 1.0, 0.0]  # [axis, angle]
  init_pos_obj: [0.4283, -0.34489, 0]
  init_axisangle_obj: [0.0022758, 0.0215909, -0.9997643, 1.5556855]  # [axis, angle]
  init_vel_obj: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  # initial position/velocity of the robot
  init_qpos_franka: [-1.7, 0.71, 0, -1.97, 1.36, 1.45, 1.74]
  init_qvel_franka: [0, 0, 0, 0, 0, 0, 0]

  # initial position/velocity of the allegro hand
  init_qpos_allegro: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  init_qvel_allegro: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  # upper/lower bounds for actions/observations which are used by gym env