_target_: vid2skill.common.drake_envs.franka_allegro_env.FrankaAllegroDrakeSystem

configs:
  _target_: vid2skill.common.config_classes.env_configs.FrankaAllegroDrakeSystemConfigs
  state_size: 59
  action_size: 23
  frame_skip: 20
  sim_dt: 0.001
  show_collision_geometries: false
  package_map:
    trifinger: "lcs_rl/drake_envs/trifinger_with_cube"

  urdfs:
    - "vid2skill/models/franka_allegro/franka_allegro.urdf"
    - "vid2skill/models/ycb/006_mustard_bottle.sdf"

  welded_links:
    - body_of_child_link: "franka_allegro"
      child_link: "panda_link0"
      body_of_parent_link: "WorldModelInstance"
      parent_link: "world"

  additional_joints: []

  contact_geoms:
    - body_1: "trifingeredu_simplified"
      link_1: "finger_tip_link_0"
      body_2: "cube"
      link_2: "cube"
      align_tangential_force_basis_to_linear_vel: false
    - body_1: "trifingeredu_simplified"
      link_1: "finger_tip_link_120"
      body_2: "cube"
      link_2: "cube"
      align_tangential_force_basis_to_linear_vel: false
    - body_1: "trifingeredu_simplified"
      link_1: "finger_tip_link_240"
      body_2: "cube"
      link_2: "cube"
      align_tangential_force_basis_to_linear_vel: false
    - body_1: "cube"
      link_1: "ground_contact_point_1"
      body_2: "WorldModelInstance"
      link_2: "world"
      align_tangential_force_basis_to_linear_vel: false
    - body_1: "cube"
      link_1: "ground_contact_point_3"
      body_2: "WorldModelInstance"
      link_2: "world"
      align_tangential_force_basis_to_linear_vel: false
    - body_1: "cube"
      link_1: "ground_contact_point_5"
      body_2: "WorldModelInstance"
      link_2: "world"
      align_tangential_force_basis_to_linear_vel: false
    - body_1: "cube"
      link_1: "ground_contact_point_7"
      body_2: "WorldModelInstance"
      link_2: "world"
      align_tangential_force_basis_to_linear_vel: false

  contact_friction_coeffs: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]


  # task related config parameters
  target_pos_obj: [0.0, 0.0, 0.0325]
  target_axisangle_obj: [0.0, 0.0, 1.0, 0.0]  # [axis, angle]
  init_pos_obj: [0.4, 0.4, 0.0955]
  init_axisangle_obj: [1.0, 0.0, 0.0, -1.5707]  # [axis, angle]
  init_vel_obj: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  # initial position/velocity of the robot
  init_qpos_franka: [-0.3, 0.71, 0, -1.97, 1.36, 1.45, 1.74]
  init_qvel_franka: [0, 0, 0, 0, 0, 0, 0]

  # initial position/velocity of the allegro hand
  init_qpos_allegro: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  init_qvel_allegro: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  # upper/lower bounds for actions/observations which are used by gym env